# Generated by Django 3.2.9 on 2021-11-18 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_mood_post'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mood',
            table='message_mood',
        ),
        migrations.AlterModelTable(
            name='post',
            table='message_post',
        ),
    ]
