# Generated by Django 3.2.9 on 2021-11-20 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20211118_2021'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mood',
            table=None,
        ),
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
