# Generated by Django 3.2.8 on 2021-11-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('star', models.IntegerField()),
                ('market_price', models.CharField(max_length=255)),
                ('selling_price', models.CharField(max_length=255)),
                ('img_url', models.CharField(max_length=255)),
                ('data_url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'klook',
                'managed': False,
            },
        ),
    ]
