# Generated by Django 3.2.8 on 2021-11-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_kkdaychanghua_kkdaychiayi_kkdaygreenisland_kkdayhsinchu_kkdayhualien_kkdaykaohsiung_kkdaykeelung_kkd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kkday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('rating_count', models.IntegerField()),
                ('star', models.FloatField()),
                ('order_count', models.IntegerField()),
                ('market_price', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('img_url', models.CharField(max_length=255)),
                ('data_url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'kkday',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Kkdaychanghua',
        ),
        migrations.DeleteModel(
            name='Kkdaychiayi',
        ),
        migrations.DeleteModel(
            name='Kkdaygreenisland',
        ),
        migrations.DeleteModel(
            name='Kkdayhsinchu',
        ),
        migrations.DeleteModel(
            name='Kkdayhualien',
        ),
        migrations.DeleteModel(
            name='Kkdaykaohsiung',
        ),
        migrations.DeleteModel(
            name='Kkdaykeelung',
        ),
        migrations.DeleteModel(
            name='Kkdaykenting',
        ),
        migrations.DeleteModel(
            name='Kkdaykinmen',
        ),
        migrations.DeleteModel(
            name='Kkdaylanyu',
        ),
        migrations.DeleteModel(
            name='Kkdayliouciou',
        ),
        migrations.DeleteModel(
            name='Kkdaymatzu',
        ),
        migrations.DeleteModel(
            name='Kkdaymiaoli',
        ),
        migrations.DeleteModel(
            name='Kkdaynantou',
        ),
        migrations.DeleteModel(
            name='Kkdaynewtaipeicity',
        ),
        migrations.DeleteModel(
            name='KkdayPenghu',
        ),
        migrations.DeleteModel(
            name='Kkdaypingtung',
        ),
        migrations.DeleteModel(
            name='Kkdaypingxi',
        ),
        migrations.DeleteModel(
            name='Kkdaytaichung',
        ),
        migrations.DeleteModel(
            name='KkdayTainan',
        ),
        migrations.DeleteModel(
            name='Kkdaytaipei',
        ),
        migrations.DeleteModel(
            name='Kkdaytaitung',
        ),
        migrations.DeleteModel(
            name='Kkdaytaoyuan',
        ),
        migrations.DeleteModel(
            name='Kkdayyilan',
        ),
        migrations.DeleteModel(
            name='Kkdayyunlin',
        ),
    ]
