# Generated by Django 3.2.9 on 2021-11-21 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_auto_20211121_1114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
