# Generated by Django 3.2.7 on 2021-10-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=255)),
                ('img_url', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('create_data', models.DateField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
