# Generated by Django 3.2.8 on 2021-10-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HinataYoutube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('videourl', models.CharField(db_column='videoUrl', max_length=255)),
                ('imgurl', models.CharField(db_column='imgUrl', max_length=255)),
                ('viewcount', models.IntegerField(db_column='viewCount')),
                ('likecount', models.IntegerField(db_column='likeCount')),
                ('dislikecount', models.IntegerField(db_column='dislikeCount')),
                ('commentcount', models.CharField(db_column='commentCount', max_length=255)),
                ('uploaddate', models.CharField(db_column='uploadDate', max_length=255)),
                ('published_date', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'hinata_youtube',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NogiYoutube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('videourl', models.CharField(db_column='videoUrl', max_length=255)),
                ('imgurl', models.CharField(db_column='imgUrl', max_length=255)),
                ('viewcount', models.IntegerField(db_column='viewCount')),
                ('likecount', models.IntegerField(db_column='likeCount')),
                ('dislikecount', models.IntegerField(db_column='dislikeCount')),
                ('commentcount', models.CharField(db_column='commentCount', max_length=255)),
                ('uploaddate', models.CharField(db_column='uploadDate', max_length=255)),
                ('published_date', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'nogi_youtube',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SakuYoutube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_collation='utf8_general_ci', max_length=255)),
                ('videourl', models.CharField(db_collation='utf8_general_ci', db_column='videoUrl', max_length=255)),
                ('imgurl', models.CharField(db_collation='utf8_general_ci', db_column='imgUrl', max_length=255)),
                ('viewcount', models.IntegerField(db_column='viewCount')),
                ('likecount', models.IntegerField(db_column='likeCount')),
                ('dislikecount', models.IntegerField(db_column='dislikeCount')),
                ('commentcount', models.CharField(db_collation='utf8_general_ci', db_column='commentCount', max_length=255)),
                ('uploaddate', models.CharField(db_collation='utf8_general_ci', db_column='uploadDate', max_length=255)),
                ('published_date', models.CharField(db_collation='utf8_general_ci', max_length=255)),
            ],
            options={
                'db_table': 'saku_youtube',
                'managed': False,
            },
        ),
    ]
