# Generated by Django 3.2.8 on 2021-10-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('zone', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('market_address', models.CharField(max_length=255)),
                ('pay_list', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'food',
                'managed': False,
            },
        ),
    ]
