# Generated by Django 3.2.8 on 2021-11-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foodpanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(db_column='shopName', max_length=255)),
                ('star', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255)),
                ('shopurl', models.CharField(db_column='shopUrl', max_length=255)),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'foodpanda',
                'managed': False,
            },
        ),
    ]
